### PR TITLE
Added drip identifier

### PR DESCRIPTION
**Pull request by royh02**
I think the emojis should work

### CODE REVIEW

**Comment by robertquitt** [comment]
You could add a test case here to make sure it works, or run it in a test server

https://github.com/royh02/csua-backend/blob/master/apps/discordbot/tests.py

**Comment by royh02** [comment]
The checks passed with the modified test.py

**Review by robertquitt — APPROVED** [review]
🥵😳😳😈💦💦👟👟👟👨‍🚀💧💧💧

**Review by robertquitt — CHANGES_REQUESTED** [review]
Fix your bug, maybe also a test asserting that no reactions are added for a generic message.

Please test your code (unit test or manual)

**Review by robertquitt — CHANGES_REQUESTED** [review]
Fix your bug, maybe also a test asserting that no reactions are added for a generic message.

Please test your code (unit test or manual)

**Comment by royh02** [comment]
Dang that was a rookie mistake. Updated now

**Comment by aninrusimha** [comment]
I'll show you how to test it after csua meeting

**Comment by aninrusimha** [comment]
I'll test it tonight, if you could join #root-staff on slack we can discuss it there.
looks good though

**Comment by royh02** [comment]
Yep I got a test server set up with @robertquitt 's help and got unit testing done (we just went over this in 61b).

**Review by aninrusimha — APPROVED** [review]

**Pull request merged**
